name: {project_name}
description: {project_description}
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:

  domain:
    path: ./domain
  core:
    path: ./core
  core_ui:
    path: ./core_ui
  data:
    path: ./data
  navigation:
    path: ./navigation

  flutter:
    sdk: flutter



dev_dependencies:
  flutter_lints: ^5.0.0

  flutter_test:
    sdk: flutter
  build_runner: ^2.4.13

flutter:
  uses-material-design: true

#  fonts:
#    - family: Inter
#      fonts:
#        - asset: core/resources/fonts/Inter.ttf
